### PR TITLE
Fix type checking

### PR DESCRIPTION
**Pull request by Endogen**

### CODE REVIEW

**Comment by throwaway-lamden** [comment]
Thanks!

**Comment by throwaway-lamden** [comment]
Might have to revert since this seems to break things; don't have time to see why right now though

**Comment by throwaway-lamden** [comment]
Ok it appears that this wasn't the cause of the things breaking; something in the test harness did change since commit 083a10f though, and I'm not sure what. I'm temporarily going to put this PR on hold while I look for that.

**Comment by Endogen** [comment]
In this fix https://github.com/throwaway-lamden/rubixdao/pull/9/commits/f3185be7bda84c726b8411290ca8e3da23975191 I actually forgot to remove some stuff and then did remove it here: https://github.com/throwaway-lamden/rubixdao/pull/9/commits/464a95a84170b6d238304cf6dbbc095b74e9061f

So both needs to be tested together or it will break if you test only the first fix. But i think everything will be put together and then tested together right? If so, then things should not break because of this.

**Comment by throwaway-lamden** [comment]
Yeah, I completely reverted the change and the tests are still breaking - a diff also shows that nothing meaningful changed since the last known-good commit (which is 083a10f)

**Pull request merged**
